spring:
  application:
    name: service

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liTvuG54hYZWUVZu
            client-secret: 35cac856926a012e120ba99f1ad2246c415eb1a5
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

  datasource:
    url: jdbc:postgresql://localhost:5432/forge-deploy-service
    username: forge_user
    password: forge_password

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: 048e51adcecaef206bdb0b11a8af5f7baef79cbf580dcf3030b8bbf33aa091b4

storage:
  s3:
    bucket-name: forge-deploy-assets
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: password
    region: us-east-1
